---
# file: roles/lamp/tasks/lamp_centos.yml

- name: install apache
  yum:
    name: httpd
    state: installed

- name: start apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: install mariadb
  yum:
    name: mariadb, mariadb-server
    state: installed

- name: start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: copy info file
  copy:
    src: info.php
    dest: /var/www/html/info.php

- name: install php
  yum:
    name: php, php-mysql, php-dba, php-devel, php-gd, php-mbstring
    state: installed

- name: restart apache
  service:
    name: httpd
    state: restarted
    enabled: yes

...
